name: 'pre-build and test devcontainer image'
on:
# workflow_dispatch:
#   inputs:
#     imageName:
#       description: 'Image name to build'
#       required: true
#       default: 'ghcr.io/lgersman/devcontainer-boilerplate'

  # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout (GitHub)
        uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pre-build image and run make ci-build in dev container
        uses: devcontainers/ci@v0.3
        with:
          push: always
          # Change this to point to your image name
          imageName: ghcr.io/lgersman/devcontainer-boilerplate
          cacheFrom: ghcr.io/lgersman/devcontainer-boilerplate
          # Change this to be your CI task/script
          runCmd: |
            echo "Using image ghcr.io/lgersman/devcontainer-boilerplate"
            pnpm install
            pnpm build
            echo "It seems to work !"

